### PR TITLE
Feature/add dog adding modal

### PR DESCRIPTION
**Pull request by Douglas-Thornton**
Finishes the profile page;

- Ability to create and edit currently logged in user.
- Ability to add and edit a list of dogs for the logged in user (or add dogs to a incomplete user mid creation)
- Ability to upload images for newly create dogs and upload photos for edited dogs.

### CODE REVIEW

**Review by Elliott127 — APPROVED** [review]
Looks good push to main

**Comment by Elliott127** [comment]
Why is the merging blocked on this @Douglas-Thornton ?

**Comment by Douglas-Thornton** [comment]
No idea; I thought protected branches were a premium feature anyway, will look into it.

**Comment by Douglas-Thornton** [comment]
Main branch was 'locked' weird; I don't remember turning that on. 🤷

**Pull request merged**
